kind: Namespace
apiVersion: v1
metadata:
  name: roboshop
---
# This role is admin role of roboshop
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop
subjects:
# You can specify more than one "subject"
- kind: User
  name: sai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: roboshop-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-eks-spot-cluster-nodegroup-NodeInstanceRole-1SJXZ56SHJJK5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::923625343454:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-14T11:31:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "19511"
  uid: d43ad974-9713-4af7-b446-6aa5bb1e4ec2

  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-reader-roboshop
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["nodes","persistentvolumes","secrets","namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-roboshop
subjects:
- kind: User
  name: sivakumar # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-reader-roboshop
  apiGroup: rbac.authorization.k8s.io
